/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mrhart1ey.gomoku.player.gui.menu;

import java.util.Stack;
import javax.swing.JComponent;
import mrhart1ey.gomoku.SingleTimePasser;

/**
 *
 * @author josh
 */
public class JoinMenuScreen extends javax.swing.JPanel {

    private final MenuScreenTransition menuScreenTransition;
    private final JComponent followOn;
    private final Stack<JComponent> menuScreenHistory;
    private final SingleTimePasser<Thread> sessionConfigurationThreadPasser;
    private final SingleTimePasser<String> hostPasser;

    /**
     * Creates new form JoinMenuScreen2
     */
    public JoinMenuScreen(MenuScreenTransition menuScreenTransition,
            JComponent followOn,
            Stack<JComponent> menuScreenHistory,
            SingleTimePasser<Thread> sessionConfigurationThreadPasser,
            SingleTimePasser<String> hostPasser) {
        this.menuScreenTransition = menuScreenTransition;
        this.followOn = followOn;
        this.menuScreenHistory = menuScreenHistory;
        this.sessionConfigurationThreadPasser = sessionConfigurationThreadPasser;
        this.hostPasser = hostPasser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hostAddress = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        connect = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Hostname");

        hostAddress.setText("localhost");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        connect.setText("Connect");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(hostAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(connect)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(connect))
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Thread sessionConfigurationHandler = sessionConfigurationThreadPasser.take();
            sessionConfigurationHandler.interrupt();
            menuScreenTransition.transition(null, menuScreenHistory.pop());
        } catch (InterruptedException ex) {
        }
    }//GEN-LAST:event_backActionPerformed

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
        // TODO add your handling code here:
        menuScreenTransition.transition(this, followOn);
        hostPasser.put(hostAddress.getText());
    }//GEN-LAST:event_connectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton connect;
    private javax.swing.JTextField hostAddress;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
