/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mrhart1ey.gomoku.player.gui.menu;

import java.util.Stack;
import javax.swing.JComponent;
import mrhart1ey.gomoku.SingleTimePasser;

/**
 *
 * @author josh
 */
public class MultiplayerMenuScreen extends javax.swing.JPanel {

    private final MenuScreenTransition menuScreenTransition;
    private final JComponent hostFollowOn;
    private final JComponent joinFollowOn;
    private final Stack<JComponent> menuScreenHistory;
    private final SingleTimePasser<Thread> choosenSessionConfigurationThread;
    private final Runnable hostSessionConfigurationHandler;
    private final Runnable joinSessionConfigurationHandler;

    /**
     * Creates new form SinglePlayerMenuScreen2
     */
    public MultiplayerMenuScreen(MenuScreenTransition menuScreenTransition,
            JComponent hostFollowOn,
            JComponent joinFollowOn,
            Stack<JComponent> menuScreenHistory,
            SingleTimePasser<Thread> choosenSessionConfigurationThread,
            Runnable hostSessionConfigurationHandler,
            Runnable joinSessionConfigurationHandler) {
        this.menuScreenTransition = menuScreenTransition;
        this.joinFollowOn = joinFollowOn;
        this.hostFollowOn = hostFollowOn;
        this.menuScreenHistory = menuScreenHistory;
        this.choosenSessionConfigurationThread = choosenSessionConfigurationThread;
        this.joinSessionConfigurationHandler = joinSessionConfigurationHandler;
        this.hostSessionConfigurationHandler = hostSessionConfigurationHandler;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        join = new javax.swing.JButton();
        host = new javax.swing.JButton();
        back = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("What would you like to do?");

        join.setText("Join");
        join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinActionPerformed(evt);
            }
        });

        host.setText("Host");
        host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(host, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back)
                            .addComponent(join, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(host)
                .addGap(18, 18, 18)
                .addComponent(join)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinActionPerformed
        // TODO add your handling code here:
        menuScreenTransition.transition(this, joinFollowOn);
        Thread sessionConfigurationThread
                = new Thread(joinSessionConfigurationHandler);

        choosenSessionConfigurationThread.put(sessionConfigurationThread);
        sessionConfigurationThread.start();
    }//GEN-LAST:event_joinActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        menuScreenTransition.transition(null, menuScreenHistory.pop());
    }//GEN-LAST:event_backActionPerformed

    private void hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostActionPerformed
        // TODO add your handling code here:
        menuScreenTransition.transition(this, hostFollowOn);
        Thread sessionConfigurationThread
                = new Thread(hostSessionConfigurationHandler);

        choosenSessionConfigurationThread.put(sessionConfigurationThread);
        sessionConfigurationThread.start();
    }//GEN-LAST:event_hostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton host;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton join;
    // End of variables declaration//GEN-END:variables
}
